version: "3.1"

services:
  site:
    image: "node:16"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    expose:
      - 5080
    ports:
      - 5080:8080
    command: "npm run serve"
